## Numpy Array Creation Methods:

In [2]:
data_list = [1,2,3]  # One-dimensional list

In [3]:
data_list

[1, 2, 3]

In [38]:
import numpy as np  #Usually people use numpy as "np"

In [5]:
arr = np.array(data_list) #We created a numpy array

In [6]:
arr

array([1, 2, 3])

In [7]:
data_list2 = [[10, 20, 30],[40, 50, 60],[70, 80, 90]] #3x3 matrix list

In [11]:
arr2 = np.array(data_list2)

In [12]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
arr3 =  np.array([1,2,3,4,5]) #Short way to create a numpy array
arr3

array([1, 2, 3, 4, 5])

## We can reach components as same as lists:

In [15]:
arr3[0]

1

In [17]:
arr3[3]

4

In [19]:
arr2[2,2]

90

In [23]:
arr2[0,1]

20

## Using different methods on numpy:

### range():

In [24]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

### zeros() and ones():
**zeros():** Creates zeros as much as the given number.\
**ones():** Creates ones as much as the given number.

In [28]:
np.zeros(10) #The "." means it gets print as float.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.zeros((2,2)) #Creates 2x2 matrix

array([[0., 0.],
       [0., 0.]])

In [34]:
np.ones((3,4)) #Creates 3x4 matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace(x,y,z):
Divides numbers between x and y into z equal parts.

In [35]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [36]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

### eye():
It creates a given number ranged matrix which its diagonals are 1.

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### random.randint / rand / randn():
Creates random integers between given range.

In [48]:
np.random.randint(0,10)

7

In [49]:
np.random.randint(15) #If you enter one value it will assume as it starts from 0

1

In [55]:
np.random.randint(1,10,5) #It will return 5 random numbers between 1-10 as array

array([2, 6, 9, 4, 4])

In [51]:
np.random.rand(5)

array([0.65877504, 0.77153648, 0.25993434, 0.14349818, 0.85542657])

In [54]:
np.random.randn(5) # It will create negative numbers too

array([-0.53651878, -1.00668938,  1.3477848 ,  1.07986558, -1.28892618])

### reshape():
To shape matrices into wanted range

In [73]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
arr.reshape(5,5) # Converts arr array into 5x5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

##### Be careful, the given range should fit the number of components:

In [75]:
arr.reshape(4,5)

ValueError: cannot reshape array of size 25 into shape (4,5)

**It gives an error because 4 times 5 equals 20. There are still 4 more components in arr array. So the multiplication of the given range, should be the same as components number.**

#  

### max(), min() and sum():

In [81]:
newArray = np.random.randint(1,100,10)
newArray

array([68, 47, 46, 32,  1, 81, 63, 19, 41, 98])

In [83]:
newArray.max() # Biggest number in the array

98

In [84]:
newArray.min() # Smallest number in the array

1

In [88]:
newArray.sum() #Sum of the numbers in the array

496

In [89]:
newArray.mean() # Mean of the numbers

49.6

### Finding indices:

In [90]:
newArray.argmax() # Finds maximum number's index

9

In [91]:
newArray.argmin() # Finds minimum number's index

4

### Finding determinant and round():
**linalg().det:** Finds determinant of a matrix\
**round():** Rounds the number

In [96]:
detArray = np.random.randint(1,100,25)
detArray

array([37, 42,  2, 25, 42, 26, 63, 28, 66, 40, 26, 16, 22, 10, 18, 48, 43,
       23, 85, 80, 37, 57,  6, 94, 34])

In [97]:
detArray = detArray.reshape(5,5)
detArray

array([[37, 42,  2, 25, 42],
       [26, 63, 28, 66, 40],
       [26, 16, 22, 10, 18],
       [48, 43, 23, 85, 80],
       [37, 57,  6, 94, 34]])

In [99]:
np.linalg.det(detArray) # Finds the determinant of the array

-102939921.99999985

In [104]:
detArray2 = np.array([[1,2],[3,4]])
detArray2

array([[1, 2],
       [3, 4]])

In [105]:
np.linalg.det(detArray2)

-2.0000000000000004

***
Let's make this look better:

In [114]:
round(np.linalg.det(detArray2)) # Rounds the number

-2