## Numpy Array Indekslenmesi ve Parçalanması:

In [17]:
import numpy as np

In [18]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr[1]

2

In [20]:
arr[1:5] # We splitted arr array 1st to 5th indices

array([2, 3, 4, 5])

In [21]:
arr[:4] # We splitted arr array 0th to 4th indices

array([1, 2, 3, 4])

In [22]:
arr[::2] #It will jump and split arr array indices two by two

array([1, 3, 5, 7, 9])

### How to change values in an array:

In [23]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

***
Let's change first three values:

In [24]:
arr[:3] = 25 # First three values are 25 now
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

***
**Note!**

In [35]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr2 = arr #Now arr2 is same as arr
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr2[:3] = 100
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [38]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

#### When we changed arr2, arr also changed. That's because when we created arr, it shows an exact point and when we created arr2 it also shows the same point as arr. So when we changed first three values or arr2, first three values of arr changed too.

***
### copy():
**If we want to create arr2 seperately we make it show another point, its own point by copying arr:**

In [40]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr2 = arr.copy()
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr2[:3] = 25
arr2

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [50]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### As you can see arr hasn't changed.

***
## Review:

In [52]:
newArray = np.arange(1,21)
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [53]:
newArray.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [55]:
newArray # It hasn't changed

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [57]:
newArray = newArray.reshape(5,4) # Now it's changed
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [58]:
newArray[0,0]

1

In [66]:
newArray[:,:2] 
#If you put comma like this it takes the first 2 numbers from each row 

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [70]:
newArray[:3,:3] # It takes first 3 numbers from the first 3 rows

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [74]:
newArray[:2,:] # First two rows

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [76]:
newArray[:2] # First two rows (again)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Filtration Numpy Arrays:

In [89]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr > 3
# Checks each values and if value bigger than 2 returns True, else False

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [91]:
booleanArray = arr > 3

In [97]:
arr[booleanArray] # It removes False values and prints True ones

array([ 4,  5,  6,  7,  8,  9, 10])

In [100]:
arr[arr > 5] # Short way to write

array([ 6,  7,  8,  9, 10])