## Basic Operations of Numpy Arrays':

In [1]:
import numpy as np

In [17]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 3, 4, 5, 6, 7])

**Addition:**

In [25]:
arr1 + arr2 # Each component will be summed up among themselves

array([12, 23, 34, 45, 56, 67])

**Note: You cannot sum up different dimensional arrays. They should have same dimension.**

In [19]:
arr1 + 10 # 10 will be added to each component of arr1

array([20, 30, 40, 50, 60, 70])

***
**Subtraction:**

In [20]:
arr1 - arr2 # Each component will be subtracted among themselves

array([ 8, 17, 26, 35, 44, 53])

In [23]:
arr2 - 15 # 15 will be subtracted from each component of arr2

array([-13, -12, -11, -10,  -9,  -8])

***
**Multiplication:**

In [21]:
arr1 * arr2 # Each component will be multiplied among themselves

array([ 20,  60, 120, 200, 300, 420])

**Note:** This actually is finding **Inner Product** in physical terms.

***
**Division:**

In [26]:
arr1 / 3 # Each component will be divided by 3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667,
       20.        ])

***
**Taking square root:**

In [28]:
np.sqrt(arr2)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131])

***
**For more functions and operations: https://docs.scipy.org/doc/**
Go > NumPy User Guide