#### Include numpy

In [3]:
import numpy as np

#### Create an array contains 5 1s

In [5]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

#### Create an array contains 5 0s

In [7]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

#### Create an array of values from 2 to 100 that can divisible by 2

In [9]:
arr = np.arange(2,101,2)
arr

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

#### Create an array that contains 5 10s

In [11]:
arr = np.ones(5)*10
arr

array([10., 10., 10., 10., 10.])

In [14]:
arr = np.ones(5)         #OTHER WAY
arr[:] = 10
arr

array([10., 10., 10., 10., 10.])

#### Create a 4x4 matrix with values from 1 to 16

In [23]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### Create a 4x4 unit matrix

In [25]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Create random integers between 0-5

In [41]:
arr = np.random.randint(0,5,5)
arr

array([0, 1, 3, 0, 2])

#### Create a 5 x 5 matrix by generating values by Gaussian Distribution (randn() function)

In [44]:
arr = np.random.randn(25).reshape(5,5)
arr

array([[-1.21656576, -0.77137879, -0.55329317,  1.10327975, -0.77565352],
       [ 1.0394513 ,  0.37980769,  0.63903132,  1.11550955, -0.86776628],
       [ 0.92616475, -0.10012283,  0.54902854,  0.73752147,  1.78589359],
       [-0.08311588,  0.47256349,  1.95671856, -0.58557711,  1.71196514],
       [ 1.27422533,  0.22474018,  0.72300231, -0.69588348,  2.19341656]])

#### Create an array of 20 elements by dividing the distance between 1 and 5 equal parts

In [48]:
arr = np.linspace(1,5,20)
arr

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

***
## Array Indexing

In [58]:
arr  = np.arange(1,101).reshape(10,10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

### Try to reach the outputs below, using index operations

### 

**1-)**\
array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],\
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],\
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],\
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],\
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],\
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [99]:
arr[4:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

***

**2-)**\
array([[ 65,  66,  67,  68,  69,  70],\
       [ 75,  76,  77,  78,  79,  80],\
       [ 85,  86,  87,  88,  89,  90],\
       [ 95,  96,  97,  98,  99, 100]])

In [70]:
arr[6:,4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

***

**3-)**\
array([[ 3,  4],\
       [13, 14],\
       [23, 24]])

In [77]:
arr[:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

***

**4-)**\
array([ 2, 12, 22])

In [120]:
arr[:3,1]

array([ 2, 12, 22])

***

**5-)**\
array([[ 2],\
       [12],\
       [22]])

In [121]:
arr[:3,1:2]

array([[ 2],
       [12],
       [22]])

***

**6-)**\
array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [146]:
arr[:10:,-1]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [148]:
arr[:,9] # OTHER WAY

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

***

## Array Operations

In [176]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [177]:
arr1

array([[4, 1, 4],
       [1, 1, 3],
       [3, 1, 0]])

In [178]:
arr2

array([[3, 3, 4],
       [4, 4, 4],
       [3, 4, 0]])

***
#### Sum up both matrices

In [179]:
arr1 + arr2

array([[7, 4, 8],
       [5, 5, 7],
       [6, 5, 0]])

***
#### Multiply both matrices

In [181]:
arr1 * arr2

array([[12,  3, 16],
       [ 4,  4, 12],
       [ 9,  4,  0]])

***
#### Find the mean of arr1 matrix

In [182]:
arr1.mean()

2.0

***
#### Find the sum of all components of arr2

In [183]:
arr2.sum()

29